[package]
name = "notes-to-anki"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "3.2.0", features = ["json"] }

[dev-dependencies]
indoc = "2.0.7"
